### ISSUE TITLE
Package will not work when included in a separate assembly.....

### ISSUE THREAD

**Issue by natiki** [totpero/DeviceDetector.NET#9]
Hi,

The package **assumes** a bunch of things:

1. It is part of a website project
2. It can write to the disk wherever it is found

![image](https://user-images.githubusercontent.com/4738140/45936626-26e4e900-bffc-11e8-8199-80c48bb18f2c.png)

Both of these mean for instance you cannot easily place it into a separate assembly (class library) that is referenced by many front end projects.

A few options spring to mind:

1. Separate package into two a) Code, b) Yml
2. Allow the data files to be access from a user configurable location (and not written as resources)

**Comment by totpero** [comment]
Hi @natiki try this: https://github.com/totpero/DeviceDetector.NET/issues/4#issuecomment-435707509

**Comment by totpero** [comment]
@natiki Is this issue fixed with last version?

**Comment by natiki** [comment]
I will come back to you.

**Comment by WellBload** [comment]
Still not fixed! I tried to use DeviceDetectorSettings.RegexesDirectory = HostingEnvironment.MapPath("~/bin/"), but not working.

**Comment by totpero** [comment]
Hi @natiki @WellBload  I just release new update and this last version include MVC sample project with your scenario. 
If this bug persist feel free to open this issue.
Also this last update include last changes from original repo.
